using CompanyManagement.Api.Data; using CompanyManagement.Api.DTOs; using CompanyManagement.Api.Models; using CompanyManagement.Api.Repositories; using CompanyManagement.Api.Services; using Microsoft.EntityFrameworkCore;
namespace CompanyManagement.Tests;
public class ServiceTests { static AppDbContext Db(){var o=new DbContextOptionsBuilder<AppDbContext>().UseInMemoryDatabase(Guid.NewGuid().ToString()).Options;return new AppDbContext(o);} static ICacheService Cache()=>new MemoryCache();
 [Fact] public async Task Get_existing_client_returns_value(){using var db=Db();db.Clientes.Add(new Cliente{Id=1,Nombre="Ana",Email="a@x.com",FechaRegistro=DateTime.UtcNow});await db.SaveChangesAsync();var s=new ClienteService(new ClienteRepository(db),Cache());Assert.NotNull(await s.Get(1));}
 [Fact] public async Task Get_missing_client_returns_null(){using var db=Db();var s=new ClienteService(new ClienteRepository(db),Cache());Assert.Null(await s.Get(99));}
 [Fact] public async Task Create_valid_client(){using var db=Db();var s=new ClienteService(new ClienteRepository(db),Cache());var r=await s.Create(new ClienteCreateDto{Nombre="Ana",Email="a@x.com"});Assert.NotNull(r.Item1);}
 [Fact] public async Task Create_duplicate_email_errors(){using var db=Db();db.Clientes.Add(new Cliente{Nombre="Ana",Email="a@x.com",FechaRegistro=DateTime.UtcNow});await db.SaveChangesAsync();var s=new ClienteService(new ClienteRepository(db),Cache());var r=await s.Create(new ClienteCreateDto{Nombre="Otra",Email="a@x.com"});Assert.NotNull(r.Item2);}
 [Fact] public async Task Create_order_for_existing_client(){using var db=Db();db.Clientes.Add(new Cliente{Id=1,Nombre="Ana",Email="a@x.com",FechaRegistro=DateTime.UtcNow});await db.SaveChangesAsync();var s=new OrdenService(new OrdenRepository(db),new ClienteRepository(db),Cache());var r=await s.Create(new OrdenCreateDto{ClienteId=1,FechaOrden=DateTime.UtcNow,MontoTotal=10});Assert.NotNull(r.Item1);}
 [Fact] public async Task Create_order_for_missing_client_errors(){using var db=Db();var s=new OrdenService(new OrdenRepository(db),new ClienteRepository(db),Cache());var r=await s.Create(new OrdenCreateDto{ClienteId=77,FechaOrden=DateTime.UtcNow,MontoTotal=10});Assert.NotNull(r.Item2);}
 [Fact] public async Task Orders_by_client_are_filtered(){using var db=Db();db.Ordenes.AddRange(new Orden{ClienteId=1,FechaOrden=DateTime.UtcNow,MontoTotal=1},new Orden{ClienteId=2,FechaOrden=DateTime.UtcNow,MontoTotal=2});await db.SaveChangesAsync();var s=new OrdenService(new OrdenRepository(db),new ClienteRepository(db),Cache());Assert.Single(await s.ForClient(1));}
 [Fact] public async Task Delete_client_with_orders_is_rejected(){using var db=Db();db.Clientes.Add(new Cliente{Id=1,Nombre="Ana",Email="a@x.com",FechaRegistro=DateTime.UtcNow});db.Ordenes.Add(new Orden{ClienteId=1,FechaOrden=DateTime.UtcNow,MontoTotal=1});await db.SaveChangesAsync();var s=new ClienteService(new ClienteRepository(db),Cache());Assert.False((await s.Delete(1)).Item1);}
 class MemoryCache:ICacheService { readonly Dictionary<string,object> d=[]; public Task<T?> Get<T>(string k)=>Task.FromResult(d.TryGetValue(k,out var v)?(T?)v:default);public Task Set<T>(string k,T v){d[k]=v!;return Task.CompletedTask;}public Task Remove(params string[] ks){foreach(var k in ks)d.Remove(k);return Task.CompletedTask;} }
}
